### ISSUE TITLE
Unknown CMake command "distortosSetConfiguration"

### ISSUE THREAD

**Issue by adamvm** [DISTORTEC/STM32F7-USB-host-ME906-lwIP-MQTT#1]
After clonning with submodules I got:

/snap/clion/107/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /home/adi/dev/distortec/STM32F7-template
CMake Error at distortos/CMakeLists.txt:19 (distortosSetConfiguration):
  Unknown CMake command "distortosSetConfiguration".

Is it some external part or problem with IDE or ... ?

**Comment by FreddieChopin** [comment]
This is because you did not specify the toolchain file and then CMake tries to configure the project for the host machine (PC).

http://distortos.org/documentation/configuring-building/ - "Common CMake pitfall" chapter at the very end.

You _MUST_ specify the toolchain file of start with an existing configuration (as stated in the README.md file from this repo) and edit it from there. I guess you don't invoke CMake yourself but your IDE does that. You either have to do one of the following:
- find where to select the toolchain file that will be used (such option may not exist or be hard to use, as in Eclipse),
- configure the project manually (from command line) and then let IDE handle just the building.

BTW - I'm not sure whether `-G "CodeBlocks - Unix Makefiles"` will work, never tried that. Let me know what are your experiences with this option.

**Comment by adamvm** [comment]
I found in File/Settings Cmake place for CMake options.
I used -C../configurations/ST_NUCLEO-F767ZI/distortosConfiguration.cmake -G "CodeBlocks - Unix Makefiles"

Now CMake reload without errors:

/snap/clion/107/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -C../configurations/ST_NUCLEO-F767ZI/distortosConfiguration.cmake -G "CodeBlocks - Unix Makefiles" /home/adi/dev/distortec/STM32F7-template
loading initial cache file ../configurations/ST_NUCLEO-F767ZI/distortosConfiguration.cmake
-- Generating /home/adi/dev/distortec/STM32F7-template/output/distortos/distortosConfiguration.cmake
-- Generating /home/adi/dev/distortec/STM32F7-template/output/distortos/include/distortos/distortosConfiguration.h
-- Generating /home/adi/dev/distortec/STM32F7-template/output/distortos/ST_NUCLEO-F767ZI.preprocessed.ld
-- Generating /home/adi/dev/distortec/STM32F7-template/output/.gitignore
-- Generating /home/adi/dev/distortec/STM32F7-template/output/include/stm32f7xx_hal_conf.h
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Doxygen needs to be installed to generate the doxygen documentation
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adi/dev/distortec/STM32F7-template/output

[Finished]
